### ISSUE TITLE
Why is the Pale Oak Sapling not listed?

### ISSUE THREAD

**Issue by Atten007** [cyklon73/RealisticGrowth#1]
Hello,

Your plugin is nice! I read its SpigotMC.org page and noticed, that the Pale Oak saplings aren’t listed there. I wanted to ask you why they aren’t listed and if you can add them. Thanks!

Kind regards,
Atten007 😊

**Comment by cyklon73** [comment]
Hello,
thank you for your positive feedback. The plugin is written for version 1.21.3 so far, the Pale Oak sappling was only available experimentally until 1.21.4. Therefore it is not yet available in the plugin. I will update the plugin to 1.21.4 now, the Pale Oak sappling will be available there then

With kind regards
Cyklon
